let fruits = ["Banana" , "Apple" , "Orange" , "Blueberries"];
fruits.shift();
fruits.sort();
console.log(fruits);
fruits.splice(3, 0, "Kiwi");
console.log(fruits);
fruits.splice(0, 1);
console.log(fruits);
fruits.reverse();
console.log(fruits);